spring:
  datasource:
    url: jdbc:postgresql://spendwise-db.ctews8y6m2ts.us-east-2.rds.amazonaws.com:5432/spendwise?sslmode=require
    username: app_user
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
server:
  port: 8080
